gaetanoAlessandrettolavoro/Activity-Tracker-FE

- src/app/componenti/daily-activity/daily-activity.component.css
- src/app/componenti/daily-activity/daily-activity.component.html
- src/app/componenti/daily-activity/daily-activity.component.ts
- src/app/page/user-home/user-home.component.ts
fixed "edit" and "delete" buttons
> fix(user-home): modified buttons in daily-activity component

- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.css
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.html
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.spec.ts
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.ts
Create page for admin change date for user specific
> Create page for admin change date for user specific

- src/app/page/emaildimenticata/email-password-dimenticata/email-password-dimenticata.component.css
> fix ui-password dimenticata

- src/app/app.routes.ts
- fixed tuttiutenti route
> [!WARNING]
> I want to remind you, in case you haven't done it yet, to update your components with the correct typing.
> fix(routes): fixed tuttiutenti route

- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.css
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.html
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
fixed attività recenti component
> fix(attRecenti):

- src/app/componenti/drop-down/drop-down.component.html
- src/app/componenti/drop-down/drop-down.component.spec.ts
- src/app/componenti/drop-down/drop-down.component.ts
> Menu module

- src/app/componenti/navbar-attrecenti/navbar-attrecenti.component.html
- src/app/componenti/navbar-attrecenti/navbar-attrecenti.component.ts
- src/app/componenti/navbarattgiornaliere/navbarattgiornaliere.component.html
- src/app/componenti/navbarattgiornaliere/navbarattgiornaliere.component.ts
- src/app/componenti/navbarimpostutente/navbarimpostutente.component.html
- src/app/componenti/navbarimpostutente/navbarimpostutente.component.ts
added drop-down in user navbars
> Add drop down

- src/app/componenti/daily-activity/daily-activity.component.html
- src/app/componenti/edit-activity-form/edit-activity-form.component.ts
- src/app/model/activityModel.ts
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.ts
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.html
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
- src/app/page/tutte-attivita/tutte-attivita.component.html
- src/app/page/tutte-attivita/tutte-attivita.component.ts
- src/app/page/user-home/user-home.component.ts
Modified components where Activity type is used
> Fix typification in Activity Model

- src/app/servizi/getusers.service.spec.ts
- src/app/servizi/getusers.service.ts
> create service-get -users

- src/app/page/admin-vis-users/admin-vis-users.component.html
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.html
> fix(fixTable):added table sorting

- package-lock.json
- package.json
- src/app/page/tutte-attivita/tutte-attivita.component.html
- src/app/page/tutte-attivita/tutte-attivita.component.ts
- src/app/servizi/getusers.service.ts
- src/app/servizi/servicelogin.service.ts
> feat(cookie): implemented CookieService

- src/app/page/admin-vis-users/admin-vis-users.component.html
- src/app/page/admin-vis-users/admin-vis-users.component.ts
- src/app/servizi/activity-user.service.spec.ts
- src/app/servizi/activity-user.service.ts
-Added a service that displays all user activities by the admin
-Implemented the service in the component.
> feat(serviceAttUser):

- src/app/componenti/navbar-admin/navbar-admin.component.css
- src/app/componenti/navbar-admin/navbar-admin.component.html
- src/app/componenti/navbar-admin/navbar-admin.component.spec.ts
- src/app/componenti/navbar-admin/navbar-admin.component.ts
create  Navbar Admin : 
-link
-button
-title
-omino
-help
> craete navbar-admin

- src/app/app.routes.ts
- src/app/componenti/admin-vis-tutte-att-users/admin-vis-tutte-att-users.component.html
- src/app/componenti/drop-down/drop-down.component.ts
- src/app/componenti/navbar-admin/navbar-admin.component.html
- src/app/page/admin-vis-users/admin-vis-users.component.css
- src/app/page/admin-vis-users/admin-vis-users.component.html
- src/app/page/admin-vis-users/admin-vis-users.component.ts
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.ts
- src/app/page/tutte-attivita/tutte-attivita.component.html
> feat(addNavbarAdmin):added navbar in home admin

- src/app/page/imposta-nuova-password/imposta-nuova-password.component.ts
Servizio che fa impostare una nuova password all'utente inserendo anche quella precedente
> create service imposta new password user add backpassword

- src/app/page/page/register/register.component.html
> fix-formregister-remove-photo

- src/app/componenti/navbar-admin/navbar-admin.component.html
- src/app/componenti/navbar-admin/navbar-admin.component.ts
- src/app/componenti/navbarutente/navbarutente.component.html
- src/app/componenti/navbarutente/navbarutente.component.ts
> fix-navbar-help

- src/app/app.component.ts
- src/app/componenti/daily-activity/daily-activity.component.html
- src/app/componenti/drop-down/drop-down.component.html
- src/app/componenti/drop-down/drop-down.component.ts
- src/app/componenti/user-manual/user-manual.component.html
- src/app/componenti/user-manual/user-manual.component.ts
> fix-routes

- src/app/page/admin-vis-users/admin-vis-users.component.html
> fix(admin-vis-users): re-added modal

- src/app/componenti/admin-vis-tutte-att-users/admin-vis-tutte-att-users.component.html
- src/app/componenti/admin-vis-tutte-att-users/admin-vis-tutte-att-users.component.ts
- src/app/componenti/sidebar-admin/sidebar-admin.component.html
- src/app/componenti/sidebar/sidebar.component.html
- src/app/page/page/register/register.component.html
> fix(modaleokiRegistrazione):

- src/app/componenti/user-task-creation/user-task-creation.component.html
- src/app/componenti/user-task-creation/user-task-creation.component.ts
> fix-data-orario

- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.css
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.ts
Add title : Admin-vis-utente-specifico 
-title: Attività di (email )
> fix-title: admin visualizza utente specifico

- src/app/page/admin-vis-users/admin-vis-users.component.css
- src/app/page/admin-vis-users/admin-vis-users.component.html
- src/app/page/admin-vis-users/admin-vis-users.component.ts
- src/app/servizi/adminservice.service.ts
filtro nome o cognome in admin visualizza tutti gli utenti
> fix filter name and surname

- src/app/componenti/sidebar/sidebar.component.html
> fix-sidebar

- src/app/app.routes.ts
- src/app/componenti/adminatoacceptusers/adminatoacceptusers.component.ts
- src/app/page/newpassword/newpassword.component.css
- src/app/page/newpassword/newpassword.component.html
- src/app/page/newpassword/newpassword.component.ts
- Fixed reset-password page: modified style, fixed errors messages and added info about password requirements
> fix(reset-password): fixed password

- src/app/page/register/register.component.html
- src/app/page/register/register.component.ts
Delete form sent success when  the user not  perform correctly  registration
> fix-register

- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.html
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
- src/app/servizi/activities-services.service.ts
> (fixfilter):update filter service

- src/app/app.component.html
- src/app/app.component.ts
- src/app/componenti/edit-activity-form/edit-activity-form.component.ts
- src/app/page/admin-vis-users/admin-vis-users.component.css
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.ts
- src/app/page/register/register.component.css
- Fixed bug in edit-activity-form
- Changed something in app.component.ts
> Bug fixing in edit-activity-form and app-component

- src/app/app.routes.ts
- src/app/componenti/sidebar/sidebar.component.html
- src/app/guardie/home.guard.ts
- src/app/guardie/user.guard.ts
- src/app/page/login/login.component.ts
> [!NOTE]
>
> It was unbeareable to see the old `/homeadmin` and `/userhome` routes
> fix(route): now `/dash-admin` and `/dash-user`  are in place

- src/app/componenti/user-task-creation/user-task-creation.component.css
modify css: user-task-creation, color white input calendar
> fix-colore calendario bottone

- src/app/page/impostazioni-utente/impostazioni-utente.component.css
- src/app/page/impostazioni-utente/impostazioni-utente.component.html
> fix-impostazioni-responsive

- src/app/page/admin-vis-users/admin-vis-users.component.css
- src/app/page/admin-vis-users/admin-vis-users.component.html
modify : css and html admin-vis-users
> fix-table-html-css-admin.vis.users

- src/app/componenti/user-manual/user-manual.component.css
- src/app/componenti/user-manual/user-manual.component.html
> fix-add-title-user-manual

- src/app/componenti/pie-chart/pie-chart.component.ts
- src/app/servizi/charts.service.ts
> fixed dates in activitiesPerUser method in charts service

- src/app/page/admin-vis-users/admin-vis-users.component.css
> fix-icon-filter

- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.css
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.html
Modify css admin-vis-utente-specifico
> fix-responsive

- src/app/page/login/login.component.ts
- src/app/servizi/logging.service.spec.ts
- src/app/servizi/logging.service.ts
loggingService in login component
> feat(logService):add and implemented

- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.ts
- src/app/page/admin-vis-users/admin-vis-users.component.ts
- src/app/page/admin-vis-utente-specifico/admin-vis-utente-specifico.component.ts
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
- src/app/page/emaildimenticata/email-password-dimenticata/email-password-dimenticata.component.ts
- src/app/page/imposta-nuova-password/imposta-nuova-password.component.ts
- src/app/page/impostazioni-utente/impostazioni-utente.component.ts
- src/app/page/newpassword/newpassword.component.ts
- src/app/page/register/register.component.ts
- src/app/page/task-crud/task-crud.component.ts
- src/app/page/tutte-attivita/tutte-attivita.component.ts
> feat(importLogService):imports logService

- src/app/page/admin-vis-users/admin-vis-users.component.html
- src/app/page/admin-vis-users/admin-vis-users.component.ts
modify e complete conflicts merge
> fixare-totalrecords-admin-vis-users

- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.css
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.html
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
Modify: attvita-recenti-utente
> report excel

- src/app/page/tutte-attivita/tutte-attivita.component.html
- src/app/page/tutte-attivita/tutte-attivita.component.ts
> feat(reportExcel):add reportService

- package-lock.json
- package.json
- src/app/app.routes.ts
- src/app/componenti/upload-excel/upload-excel.component.css
- src/app/componenti/upload-excel/upload-excel.component.html
- src/app/componenti/upload-excel/upload-excel.component.spec.ts
- src/app/componenti/upload-excel/upload-excel.component.ts
- src/app/servizi/defines.ts
- src/index.html
- src/styles.css
- tailwind.config.js
and implemented tailwind framework
> Upload file excel

- src/app/page/admin-vis-users/admin-vis-users.component.ts
- src/app/page/attivita-recenti-utente/attivita-recenti-utente/attivita-recenti-utente.component.ts
- src/app/page/tutte-attivita/tutte-attivita.component.ts
- src/app/servizi/defines.ts
> fix date field in csv ed excel file

- src/app/page/modale-impostazioni-inquadramento/modale-impostazioni-inquadramento.component.html
- src/app/page/modale-impostazioni-inquadramento/modale-impostazioni-inquadramento.component.spec.ts
- src/app/page/modale-impostazioni-inquadramento/modale-impostazioni-inquadramento.component.ts
- src/app/page/modale-impostazioni-qualifica/modale-impostazioni-qualifica.component.html
- src/app/page/modale-impostazioni-qualifica/modale-impostazioni-qualifica.component.spec.ts
- src/app/page/modale-impostazioni-qualifica/modale-impostazioni-qualifica.component.ts
modale  impostazioni per l'inquadramento e per la qualifica
> modali impostazioni-inquadramento e qualifica

- src/app/componenti/dropdown-inquadramento/dropdown-inquadramento.component.html
- src/app/componenti/dropdown-inquadramento/dropdown-inquadramento.component.ts
- src/app/componenti/dropdown-qualifica/dropdown-qualifica.component.html
- src/app/componenti/dropdown-qualifica/dropdown-qualifica.component.ts
- src/app/page/register/register.component.css
- src/app/page/register/register.component.html
- src/app/page/register/register.component.ts
modify  project : register-dropdown
> fix-register.dropdown-corretto

- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.css
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.html
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.ts
modify page adminmodedatiuserspe
> fix della pagina admin modifica i dati dell'utente specifico

- src/app/componenti/adminatoacceptusers/adminatoacceptusers.component.html
- src/app/componenti/adminatoacceptusers/adminatoacceptusers.component.ts
> fix-reload

- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.html
- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.ts
> fix-admin-mode-dati-user-spe

- src/app/page/admin-mode-dati-user-spe/admin-mode-dati-user-spe.component.html
- src/app/page/impostazioni-utente/impostazioni-utente.component.html
le date  sono state corrette in admin-mode-dati-userspe 
In impostazioni e corretta solo quella di assunzione
> (fix date)  correct in admin-mode-dati-userspe end one correct in  Settings
